# Generated by Django 2.2.3 on 2019-09-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_auto_20190805_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='typeOfEvent',
            field=models.IntegerField(choices=[(1, 'Adição de bloco.'), (2, 'Exclusão de bloco.'), (3, 'Inserção de minerador.'), (4, 'Exclusão de minerador.'), (5, 'Ocorrência de fork.')], help_text='Tipo de evento.'),
        ),
    ]
