# Generated by Django 2.2.3 on 2019-09-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_auto_20190911_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
